import { host } from "../globalRoutes";

export const addPlacementEventForm = `${host}/placement/api/placement/`;
export const fetchApplicationsRoute = `${host}/placement/api/student-applications/`;
export const handleStatusChangeRoute = `${host}/placement/api/student-applications/`;
export const downloadExcelRoute = `${host}/placement/api/download-applications/`;
export const submitNextRoundDetailsRoute = `${host}/placement/api/nextround/`;
export const downloadCVRoute = `${host}/placement/api/generate-cv/`;
export const calendarEventsRoute = `${host}/placement/api/calender/`;
export const fetchPlacementStatsRoute = `${host}/placement/api/statistics/`;
export const deletePlacementStatsRoute = `${host}/placement/api/delete-statistics/`;
export const fetchPlacementScheduleRoute = `${host}/placement/api/placement/`;
export const fetchTimeLineRoute = `${host}/placement/api/timeline/`;
export const fetchDebaredlistRoute = `${host}/placement/api/debared-students/`;
export const debarredStatusRoute = `${host}/placement/api/debared-status/`;
export const fetchFieldsSubmitformRoute = `${host}/placement/api/add-field/`;
export const fetchRestrictionsRoute = `${host}/placement/api/restrictions/`;
export const fetchRegistrationRoute = `${host}/placement/api/registration/`;
export const ApplyForPlacementRoute = `${host}/placement/api/apply-for-placement/`;
export const fetchFormFieldsRoute = `${host}/placement/api/form-fields/`;
export const sendNotificationRoute = `${host}/notifications/api/placement_cell_notification/`;
